# Generated by Django 5.2.6 on 2025-09-04 09:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nome')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message="Número de telefone deve estar no formato: '+258840000000'. Até 15 dígitos permitidos.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Telefone')),
                ('service', models.CharField(max_length=120, verbose_name='Serviço')),
                ('message', models.TextField(verbose_name='Mensagem')),
                ('consent', models.BooleanField(default=False, verbose_name='Consentimento')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Submission',
                'verbose_name_plural': 'Submissions',
                'ordering': ['-created_at'],
            },
        ),
    ]
