# Generated by Django 5.2.5 on 2025-10-06 06:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='phone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message="Número de telefone deve estar no formato: '+258840000000'. Até 09 dígitos permitidos.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Telefone'),
        ),
    ]
