# Generated by Django 5.2.5 on 2025-11-05 20:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0002_alter_submission_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, validators=[django.core.validators.EmailValidator(message='Email inválido')], verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='message',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(10, 'Mensagem deve ter pelo menos 10 caracteres')], verbose_name='Mensagem'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='name',
            field=models.CharField(max_length=120, validators=[django.core.validators.MinLengthValidator(2, 'Nome deve ter pelo menos 2 caracteres')], verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='phone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message="Número de telefone deve estar no formato: '+258840000000'. Até 15 dígitos permitidos.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='service',
            field=models.CharField(db_index=True, max_length=120, verbose_name='Serviço'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['-created_at', 'email'], name='submissions_created_0266d7_idx'),
        ),
    ]
