# Generated by Django 5.2.5 on 2025-11-05 21:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0003_submission_updated_at_alter_submission_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='submission',
            options={'ordering': ['-created_at'], 'verbose_name': 'Submissão', 'verbose_name_plural': 'Submissões'},
        ),
        migrations.AlterField(
            model_name='submission',
            name='consent',
            field=models.BooleanField(default=False, help_text='Concordo em receber comunicações da CPTec Academy', verbose_name='Consentimento'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='Data e hora em que a submissão foi criada', verbose_name='Data de Criação'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='email',
            field=models.EmailField(db_index=True, help_text='Email para contato e envio de informações', max_length=254, validators=[django.core.validators.EmailValidator(message='Email inválido')], verbose_name='Endereço de Email'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='message',
            field=models.TextField(help_text='Mensagem adicional ou dúvidas (mínimo 10 caracteres)', validators=[django.core.validators.MinLengthValidator(10, 'Mensagem deve ter pelo menos 10 caracteres')], verbose_name='Mensagem'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='name',
            field=models.CharField(help_text='Nome completo do solicitante', max_length=120, validators=[django.core.validators.MinLengthValidator(2, 'Nome deve ter pelo menos 2 caracteres')], verbose_name='Nome Completo'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='phone',
            field=models.CharField(help_text='Formato: +258840000000 (até 15 dígitos)', max_length=20, validators=[django.core.validators.RegexValidator(message="Número de telefone deve estar no formato: '+258840000000'. Até 15 dígitos permitidos.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Telefone de Contato'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='service',
            field=models.CharField(db_index=True, help_text='Tipo de curso ou serviço de interesse', max_length=120, verbose_name='Serviço Solicitado'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Data e hora da última modificação', verbose_name='Última Atualização'),
        ),
    ]
