# Generated by Django 5.2.5 on 2025-10-02 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=200)),
                ('documento', models.CharField(max_length=50)),
                ('curso', models.CharField(max_length=200)),
                ('duracao', models.CharField(max_length=50)),
                ('carga_horaria', models.CharField(max_length=50)),
                ('data_conclusao', models.DateField()),
                ('codigo', models.CharField(max_length=100, unique=True)),
                ('ano', models.CharField(max_length=10)),
                ('status', models.CharField(default='Aprovado', max_length=20)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='certifications/')),
                ('depoimento', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
