# Generated by Django 5.2.5 on 2025-10-07 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='codigo_unico',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
    ]
