# Generated by Django 5.2.5 on 2025-10-14 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certifications', '0002_certification_codigo_unico'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certification',
            name='codigo_unico',
        ),
        # migrations.RemoveField(
        #     model_name='certification',
        #     name='depoimento',
        # ),
    ]
