# Generated by Django 5.2.5 on 2025-10-15 10:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certifications', '0003_remove_certification_codigo_unico_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
