# Generated by Django 5.2.5 on 2025-10-15 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certifications', '0004_certification_uuid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certification',
            options={'verbose_name': 'Certificação', 'verbose_name_plural': 'Certificações'},
        ),
        migrations.RemoveField(
            model_name='certification',
            name='uuid',
        ),
        migrations.AlterField(
            model_name='certification',
            name='unique_link',
            field=models.CharField(blank=True, editable=False, max_length=100, null=True, unique=True),
        ),
        migrations.AlterModelTable(
            name='certification',
            table='certifications_certification',
        ),
    ]
