# Generated by Django 5.2.5 on 2025-10-15 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certifications', '0005_alter_certification_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='certification',
            table=None,
        ),
    ]
