# Generated by Django 5.2.5 on 2025-10-16 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certifications', '0006_alter_certification_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='modulo',
            field=models.CharField(blank=True, help_text='Informe o nome do módulo (ex: Módulo de Contabilidade).', max_length=100, null=True, verbose_name='Módulo (opcional)'),
        ),
    ]
