# Generated by Django 5.2.5 on 2025-10-16 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certifications', '0007_certification_modulo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certification',
            name='modulo',
        ),
        migrations.AddField(
            model_name='certification',
            name='declaracao',
            field=models.TextField(blank=True, help_text='Texto da declaração que será exibido no certificado.', null=True),
        ),
        migrations.AddField(
            model_name='certification',
            name='tem_modulos',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('certification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modulos', to='certifications.certification')),
            ],
            options={
                'verbose_name': 'Módulo',
                'verbose_name_plural': 'Módulos',
            },
        ),
    ]
