# Generated by Django 5.2.5 on 2025-10-16 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certifications', '0009_certification_modulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='descricao',
            field=models.TextField(blank=True, help_text='Adicione uma descrição detalhada para esta certificação.', null=True),
        ),
    ]
