# Generated by Django 5.2.5 on 2025-10-16 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certifications', '0010_certification_descricao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certification',
            name='tem_modulos',
        ),
        migrations.AlterField(
            model_name='certification',
            name='ano',
            field=models.CharField(max_length=10, verbose_name='Ano de Conclusão'),
        ),
        migrations.AlterField(
            model_name='certification',
            name='carga_horaria',
            field=models.CharField(max_length=50, verbose_name='Carga Horária'),
        ),
        migrations.AlterField(
            model_name='certification',
            name='codigo',
            field=models.CharField(max_length=100, unique=True, verbose_name='Código da Certificação'),
        ),
        migrations.AlterField(
            model_name='certification',
            name='curso',
            field=models.CharField(max_length=200, verbose_name='Curso'),
        ),
        migrations.AlterField(
            model_name='certification',
            name='data_conclusao',
            field=models.DateField(verbose_name='Data de Conclusão'),
        ),
        migrations.AlterField(
            model_name='certification',
            name='declaracao',
            field=models.TextField(blank=True, help_text='Texto da declaração que será exibido no Site.', null=True, verbose_name='Declaração'),
        ),
        migrations.AlterField(
            model_name='certification',
            name='descricao',
            field=models.TextField(blank=True, help_text='Adicione uma descrição detalhada para esta certificação.', null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='certification',
            name='documento',
            field=models.CharField(max_length=50, verbose_name='Documento de Identificação'),
        ),
        migrations.AlterField(
            model_name='certification',
            name='duracao',
            field=models.CharField(max_length=50, verbose_name='Duração do Curso'),
        ),
        migrations.AlterField(
            model_name='certification',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='certifications/', verbose_name='Foto do Estudante'),
        ),
        migrations.AlterField(
            model_name='certification',
            name='nome_completo',
            field=models.CharField(max_length=200, verbose_name='Nome Completo'),
        ),
        migrations.AlterField(
            model_name='certification',
            name='status',
            field=models.CharField(default='Aprovado', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='certification',
            name='unique_link',
            field=models.CharField(blank=True, editable=False, max_length=100, null=True, unique=True, verbose_name='Link Único'),
        ),
        migrations.DeleteModel(
            name='Modulo',
        ),
    ]
