# Generated by Django 5.2.5 on 2025-10-17 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certifications', '0011_remove_certification_tem_modulos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certification',
            name='modulo',
        ),
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do Módulo')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição do Módulo')),
                ('certification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modulos', to='certifications.certification', verbose_name='Certificação')),
            ],
            options={
                'verbose_name': 'Módulo',
                'verbose_name_plural': 'Módulos',
            },
        ),
    ]
