# Generated by Django 5.2.5 on 2025-10-17 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certifications', '0012_remove_certification_modulo_modulo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modulo',
            name='descricao',
        ),
    ]
