# Generated by Django 5.2.5 on 2025-11-05 20:35

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certifications', '0013_remove_modulo_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Criado em'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='certification',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
        migrations.AlterField(
            model_name='certification',
            name='codigo',
            field=models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Código da Certificação'),
        ),
        migrations.AlterField(
            model_name='certification',
            name='curso',
            field=models.CharField(db_index=True, max_length=200, validators=[django.core.validators.MinLengthValidator(3, 'Nome do curso deve ter pelo menos 3 caracteres')], verbose_name='Curso'),
        ),
        migrations.AlterField(
            model_name='certification',
            name='data_conclusao',
            field=models.DateField(db_index=True, verbose_name='Data de Conclusão'),
        ),
        migrations.AlterField(
            model_name='certification',
            name='documento',
            field=models.CharField(db_index=True, max_length=50, verbose_name='Documento de Identificação'),
        ),
        migrations.AlterField(
            model_name='certification',
            name='nome_completo',
            field=models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(3, 'Nome deve ter pelo menos 3 caracteres')], verbose_name='Nome Completo'),
        ),
        migrations.AlterField(
            model_name='certification',
            name='status',
            field=models.CharField(choices=[('Aprovado', 'Aprovado'), ('Reprovado', 'Reprovado'), ('Em Andamento', 'Em Andamento')], default='Aprovado', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='certification',
            name='unique_link',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=100, null=True, unique=True, verbose_name='Link Único'),
        ),
    ]
