# Generated by Django 5.2.5 on 2025-11-05 21:14

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certifications', '0014_certification_created_at_certification_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modulo',
            options={'verbose_name': 'Módulo do Curso', 'verbose_name_plural': 'Módulos dos Cursos'},
        ),
        migrations.AlterField(
            model_name='certification',
            name='ano',
            field=models.CharField(help_text='Ano da certificação', max_length=10, verbose_name='Ano de Conclusão'),
        ),
        migrations.AlterField(
            model_name='certification',
            name='carga_horaria',
            field=models.CharField(help_text='Total de horas do curso', max_length=50, verbose_name='Carga Horária Total'),
        ),
        migrations.AlterField(
            model_name='certification',
            name='codigo',
            field=models.CharField(db_index=True, help_text='Código único para validação (gerado automaticamente se vazio)', max_length=100, unique=True, verbose_name='Código da Certificação'),
        ),
        migrations.AlterField(
            model_name='certification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Data e hora de criação do registro', verbose_name='Data de Criação'),
        ),
        migrations.AlterField(
            model_name='certification',
            name='curso',
            field=models.CharField(db_index=True, help_text='Título completo do curso realizado', max_length=200, validators=[django.core.validators.MinLengthValidator(3, 'Nome do curso deve ter pelo menos 3 caracteres')], verbose_name='Nome do Curso'),
        ),
        migrations.AlterField(
            model_name='certification',
            name='data_conclusao',
            field=models.DateField(db_index=True, help_text='Data em que o curso foi concluído', verbose_name='Data de Conclusão'),
        ),
        migrations.AlterField(
            model_name='certification',
            name='declaracao',
            field=models.TextField(blank=True, help_text='Texto personalizado que será exibido na declaração pública', null=True, verbose_name='Texto da Declaração'),
        ),
        migrations.AlterField(
            model_name='certification',
            name='descricao',
            field=models.TextField(blank=True, help_text='Informações adicionais sobre a certificação e conquistas', null=True, verbose_name='Descrição Detalhada'),
        ),
        migrations.AlterField(
            model_name='certification',
            name='documento',
            field=models.CharField(db_index=True, help_text='BI, Passaporte ou outro documento oficial', max_length=50, verbose_name='Documento de Identificação'),
        ),
        migrations.AlterField(
            model_name='certification',
            name='duracao',
            field=models.CharField(help_text='Ex: 40 horas, 3 meses, etc.', max_length=50, verbose_name='Duração do Curso'),
        ),
        migrations.AlterField(
            model_name='certification',
            name='foto',
            field=models.ImageField(blank=True, help_text='Foto tipo passe (opcional)', null=True, upload_to='certifications/', verbose_name='Foto do Estudante'),
        ),
        migrations.AlterField(
            model_name='certification',
            name='nome_completo',
            field=models.CharField(help_text='Nome completo conforme documento de identificação', max_length=200, validators=[django.core.validators.MinLengthValidator(3, 'Nome deve ter pelo menos 3 caracteres')], verbose_name='Nome Completo do Estudante'),
        ),
        migrations.AlterField(
            model_name='certification',
            name='status',
            field=models.CharField(choices=[('Aprovado', 'Aprovado'), ('Reprovado', 'Reprovado'), ('Em Andamento', 'Em Andamento')], default='Aprovado', help_text='Status atual do estudante no curso', max_length=20, verbose_name='Status da Certificação'),
        ),
        migrations.AlterField(
            model_name='certification',
            name='unique_link',
            field=models.CharField(blank=True, db_index=True, editable=False, help_text='Gerado automaticamente ao salvar', max_length=100, null=True, unique=True, verbose_name='Link Único de Compartilhamento'),
        ),
        migrations.AlterField(
            model_name='certification',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Data e hora da última modificação', verbose_name='Última Atualização'),
        ),
        migrations.AlterField(
            model_name='modulo',
            name='certification',
            field=models.ForeignKey(help_text='Certificação à qual este módulo pertence', on_delete=django.db.models.deletion.CASCADE, related_name='modulos', to='certifications.certification', verbose_name='Certificação Relacionada'),
        ),
        migrations.AlterField(
            model_name='modulo',
            name='nome',
            field=models.CharField(help_text='Título do módulo ou unidade do curso', max_length=200, verbose_name='Nome do Módulo'),
        ),
    ]
